version: "3.8"

services:
  # üåê API principal - PROD
  exp-api-prod:
    container_name: experiencia-api-prod
    build:
      context: ../..
      dockerfile: API/Dockerfile
    restart: always
    env_file:
      - .env.prod
    ports:
      - "5103:8080"
    networks:
      - network_experiencesig
    labels:
      - com.experienciasig.environment=prod

networks:
  network_experiencesig:
    external: true
