version: "3.8"

services:
  # üåê API principal - DEVELOP
  exp-api-develop:
    container_name: experiencia-api-develop
    build:
      context: ../..     # Ruta al Dockerfile desde Devops/develop
      dockerfile: API/Dockerfile
    restart: always
    env_file:
      - .env.dev
    ports:
      - "5100:8080"
    networks:
      - network_experiencesig
    labels:
      - com.experienciasig.environment=develop

networks:
  network_experiencesig:
    external: true
